# -*- mode: makefile -*-

# Where to install and to find ELINA
# ($(PREFIX)/include, $(PREFIX)/lib)
#
ELINA_PREFIX = /usr/local


# Where to find GMP ($(GMP_PREFIX)/include, ($GMP_PREFIX)/lib
#
GMP_PREFIX = /usr/local

# Where to find MPFR ($(MPFR_PREFIX)/include, ($MPFR_PREFIX)/lib
#
MPFR_PREFIX = /usr/local

# C compilation flags
CFLAGS = \
-Wcast-qual -Wswitch -Werror-implicit-function-declaration \
-Wall -Wextra -Wundef -Wbad-function-cast -Wcast-align -Wstrict-prototypes \
-Wno-unused \
-std=c99 -U__STRICT_ANSI__ \
-fPIC -O3 -DNDEBUG

# Architecture specific flags
AFLAGS := -D_GNU_SOURCE -pthread -fno-tree-vectorize -m64 -march=native
